// Import images at the top of your file
import CMDImage from '../assets/images/CMD.jpg';
import NamoImage from '../assets/images/Namo.jpg';
import RebelionImage from '../assets/images/rebelion.jpg';

export const VideoList = [
    {
        id: '1',
        name: 'Basics of Command Line (CMD)',
        image: CMDImage,
        embedLink: "https://www.youtube.com/embed/QZ71hx19qcg?si=4dmdcRYWxdo1HSIc",
        instructorname: "Rebilion Coder",
        instructorImage: RebelionImage,
        instructorBio: 'Currently working as an SDE at a prestigious company, Aman Shrivastava, also known by his online persona Rebilion Coder, is knowledgeable in a variety of tech stack areas, such as web development, web scraping, and data science.',
    },
    {
        id: '2',
        name: 'PM Speech Analysis Project overview',
        image: NamoImage,
        embedLink: 'https://www.youtube.com/embed/WIOVqO8xqts?si=ZOfTn4kKGUkVuU86',
        instructorname: "Rebilion Coder",
        instructorImage: RebelionImage,
        instructorBio: 'Currently working as an SDE at a prestigious company, Aman Shrivastava, also known by his online persona Rebilion Coder, is knowledgeable in a variety of tech stack areas, such as web development, web scraping, and data science.',
    },
    {
        id: '3',
        name: 'Basics of Command Line (CMD)',
        image: CMDImage,
        embedLink: "https://www.youtube.com/embed/QZ71hx19qcg?si=4dmdcRYWxdo1HSIc",
        instructorname: "Rebilion Coder",
        instructorImage: RebelionImage,
        instructorBio: 'Currently working as an SDE at a prestigious company, Aman Shrivastava, also known by his online persona Rebilion Coder, is knowledgeable in a variety of tech stack areas, such as web development, web scraping, and data science.',
    },
    {
        id: '4',
        name: 'PM Speech Analysis Project overview',
        image: NamoImage,
        embedLink: 'https://www.youtube.com/embed/WIOVqO8xqts?si=ZOfTn4kKGUkVuU86',
        instructorname: "Rebilion Coder",
        instructorImage: RebelionImage,
        instructorBio: 'Currently working as an SDE at a prestigious company, Aman Shrivastava, also known by his online persona Rebilion Coder, is knowledgeable in a variety of tech stack areas, such as web development, web scraping, and data science.',
    },
    {
        id: '5',
        name: 'Basics of Command Line (CMD)',
        image: CMDImage,
        embedLink: "https://www.youtube.com/embed/QZ71hx19qcg?si=4dmdcRYWxdo1HSIc",
        instructorname: "Rebilion Coder",
        instructorImage: RebelionImage,
        instructorBio: 'Currently working as an SDE at a prestigious company, Aman Shrivastava, also known by his online persona Rebilion Coder, is knowledgeable in a variety of tech stack areas, such as web development, web scraping, and data science.',
    },
    {
        id: '6',
        name: 'PM Speech Analysis Project overview',
        image: NamoImage,
        embedLink: 'https://www.youtube.com/embed/WIOVqO8xqts?si=ZOfTn4kKGUkVuU86',
        instructorname: "Rebilion Coder",
        instructorImage: RebelionImage,
        instructorBio: 'Currently working as an SDE at a prestigious company, Aman Shrivastava, also known by his online persona Rebilion Coder, is knowledgeable in a variety of tech stack areas, such as web development, web scraping, and data science.',
    },
    {
        id: '7',
        name: 'Basics of Command Line (CMD)',
        image: CMDImage,
        embedLink: "https://www.youtube.com/embed/QZ71hx19qcg?si=4dmdcRYWxdo1HSIc",
        instructorname: "Rebilion Coder",
        instructorImage: RebelionImage,
        instructorBio: 'Currently working as an SDE at a prestigious company, Aman Shrivastava, also known by his online persona Rebilion Coder, is knowledgeable in a variety of tech stack areas, such as web development, web scraping, and data science.',
    },
    {
        id: '8',
        name: 'PM Speech Analysis Project overview',
        image: NamoImage,
        embedLink: 'https://www.youtube.com/embed/WIOVqO8xqts?si=ZOfTn4kKGUkVuU86',
        instructorname: "Rebilion Coder",
        instructorImage: RebelionImage,
        instructorBio: 'Currently working as an SDE at a prestigious company, Aman Shrivastava, also known by his online persona Rebilion Coder, is knowledgeable in a variety of tech stack areas, such as web development, web scraping, and data science.',
    },
    {
        id: '9',
        name: 'Basics of Command Line (CMD)',
        image: CMDImage,
        embedLink: "https://www.youtube.com/embed/QZ71hx19qcg?si=4dmdcRYWxdo1HSIc",
        instructorname: "Rebilion Coder",
        instructorImage: RebelionImage,
        instructorBio: 'Currently working as an SDE at a prestigious company, Aman Shrivastava, also known by his online persona Rebilion Coder, is knowledgeable in a variety of tech stack areas, such as web development, web scraping, and data science.',
    },
    {
        id: '10',
        name: 'PM Speech Analysis Project overview',
        image: NamoImage,
        embedLink: 'https://www.youtube.com/embed/WIOVqO8xqts?si=ZOfTn4kKGUkVuU86',
        instructorname: "Rebilion Coder",
        instructorImage: RebelionImage,
        instructorBio: 'Currently working as an SDE at a prestigious company, Aman Shrivastava, also known by his online persona Rebilion Coder, is knowledgeable in a variety of tech stack areas, such as web development, web scraping, and data science.',
    },
    {
        id: '11',
        name: 'Basics of Command Line (CMD)',
        image: CMDImage,
        embedLink: "https://www.youtube.com/embed/QZ71hx19qcg?si=4dmdcRYWxdo1HSIc",
        instructorname: "Rebilion Coder",
        instructorImage: RebelionImage,
        instructorBio: 'Currently working as an SDE at a prestigious company, Aman Shrivastava, also known by his online persona Rebilion Coder, is knowledgeable in a variety of tech stack areas, such as web development, web scraping, and data science.',
    },
    {
        id: '12',
        name: 'PM Speech Analysis Project overview',
        image: NamoImage,
        embedLink: 'https://www.youtube.com/embed/WIOVqO8xqts?si=ZOfTn4kKGUkVuU86',
        instructorname: "Rebilion Coder",
        instructorImage: RebelionImage,
        instructorBio: 'Currently working as an SDE at a prestigious company, Aman Shrivastava, also known by his online persona Rebilion Coder, is knowledgeable in a variety of tech stack areas, such as web development, web scraping, and data science.',
    },
    // Add more video objects as needed
];
